config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: 'create'
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2a7792d493.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit :class => 'btn btn-primary'%>
<% end %>

app/views/tasks/edit.html.erb
<!-- copy creation form -->
<h1>Edit task</h1>
<%= render "form" %>

app/views/tasks/index.html.erb
<h1>Index of tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <li>  <%= link_to task.title, task_path(task.id)%>
    </li>
    <% end %>
  </ul>

    <%= link_to "Add a new task", create_path %>

app/views/tasks/new.html.erb
<h1>Create new task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.id %> - <%= @task.title %></h1>

<ul>
  <li>
    <%= @task.details %>

      <%if @task.completed %>
        <i class="fas fa-clipboard-check"></i>
      <% else %>
        <i class="far fa-clipboard"></i>
      <% end %>
    <%= link_to "edit task", edit_path %>
    <%= link_to "Delete #{@task.title}",
        task_path(@task),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
  </li>

<%= link_to "Back to tasks list", tasks_path %>


</ul>